name: Test tap-nasa

on:
  push:
    branches: [main]
    paths:
      - tap_nasa/**
      - tests/**
      - pyproject.toml
      - tox.ini
      - uv.lock
      - .github/workflows/test.yml
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - tap_nasa/**
      - tests/**
      - pyproject.toml
      - tox.ini
      - uv.lock
      - .github/workflows/test.yml
  workflow_dispatch:
  schedule:
  # Run weekly on Monday at 12:00 PM UTC
  - cron: "0 12 * * 1"

env:
  FORCE_COLOR: "1"
  # renovate: datasource=pypi depName=tox
  TOX_VERSION: 4.31.0
  # renovate: datasource=pypi depName=tox-uv
  TOX_UV_VERSION: 1.29.0
  # renovate: datasource=pypi depName=uv
  UV_VERSION: 0.9.2

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - "3.14"
        - "3.13"
        - "3.12"
        - "3.11"

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
      id: setup-python
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true
    - uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6.8.0
      with:
        version: ${{ env.UV_VERSION }}
    - name: Run
      env:
        UV_PYTHON: ${{ steps.setup-python.outputs.python-path }}
        TAP_NASA_API_KEY: ${{ secrets.TAP_NASA_API_KEY }}
      run: >
        uvx
        --with tox-uv==${{ env.TOX_UV_VERSION }}
        --with tox==${{ env.TOX_VERSION }}
        tox -e ${{ matrix.python-version }}

  lint:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
      id: setup-python
      with:
        python-version: 3.x
    - uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6.8.0
      with:
        version: ${{ env.UV_VERSION }}
    - env:
        UV_PYTHON: ${{ steps.setup-python.outputs.python-path }}
      run: uv tool install --with tox-uv==${{ env.TOX_UV_VERSION }} --from tox==${{ env.TOX_VERSION }} tox
    - name: Static type checking
      run: tox -e typing
    - name: Unused, missing and transitive dependencies
      run: tox -e dependencies
